server:
  port: ${BOOT_SERVER_PORT:8233}

spring:
  web:
    resources:
      static-locations: classpath:/static/dist/
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB

logging:
  level:
    root: info
    com.xizeyoupan: debug