on:
  push:
  repository_dispatch:
    types: [ VUE_UPDATED ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir vue
      - run: mkdir springboot

      - uses: actions/checkout@v2
        with:
          path: vue
          repository: 'xizeyoupan/remote-clipboard-vue'

      - uses: actions/checkout@v2
        with:
          path: springboot

      - name: Delete .gitignore for railway docker build
        run: rm -f $GITHUB_WORKSPACE/springboot/.gitignore

      - uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Build vue and copy dist
        run: |
          cd $GITHUB_WORKSPACE/vue
          npm install
          npm run build
          mkdir $GITHUB_WORKSPACE/springboot/src/main/resources/static
          cp -r $GITHUB_WORKSPACE/vue/dist $GITHUB_WORKSPACE/springboot/src/main/resources/static

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Package jar
        run: |
          cd $GITHUB_WORKSPACE/springboot
          mvn -B package

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.workspace }}/springboot
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/remoteclipboard:latest

      # - name: Depoly to okteto, using docker-compose.yml
      #   run: |
      #     curl https://get.okteto.com -sSfL | sh
      #     okteto login --token ${{ secrets.OKTETO_TOKEN }}
      #     cd $GITHUB_WORKSPACE/springboot
      #     okteto namespace
      #     okteto stack deploy --no-cache --wait

      # - name: Depoly to railway, using Dockerfile
      #   run: |
      #     npm i -g @railway/cli
      #     railway link 7a3e56a7-37e5-4a9b-8c7b-5815432176f5
      #     cd $GITHUB_WORKSPACE/springboot
      #     railway up
      #   env:
      #     RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Depoly to flyio, using fly.toml
        uses: superfly/flyctl-actions@master
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        with:
          args: "deploy ./springboot"
